
title: My Resume
url: 'http://ankit.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Ankit Swarnkar  ## put your name
title: 'Data Science Graduate Student'  ## your title
location: Indiana University, Bloomington


## Social Profiles
facebook: https://www.facebook.com/ankit.swarnkar  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/ankitswarnkar/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
